// This protobuf file describes the layout of data storage for Kiwi.
// The storage layout follows an LSM-Tree like structure, consisting of these types:
// 1. Table: Equivalent to a Redis DB; Kiwi makes a separate folder per table.
// 2. Part : Each table's data is separated into multiple parts (SSTables); each part is an immutable file containing
//           an indexed list of keys and values with a slotted-page structure. Parts are named using UUIDs.
//           Each part points to its next and previous parts, allowing both-way iterations.
//           When the Kiwi memory table is full, it is flushed to disk as a new part.
//
//  Parts are self-contained files with the following structure in order:
//  - Header:     Metadata about the part, including offsets to key sections within the file.
//  - Skip Index: A sparse index of the first key of each block and its offsets.
//  - BF Index:   An optional Bloom filter for quick key existence checks per each block.
//  - Data Section: Actual key-value pairs, stored in a slotted-page format.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: layout.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Part header is always at the beginning of a part file.
type PartHeader struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                                          // Part's ID; sorted by time; File's name is <id>.part
	NextPart          int64 `protobuf:"varint,2,opt,name=next_part,json=nextPart,proto3" json:"next_part,omitempty"`                              // ID of the next part; empty if this is the last part.
	PrevPart          int64 `protobuf:"varint,3,opt,name=prev_part,json=prevPart,proto3" json:"prev_part,omitempty"`                              // ID of the previous part; empty if this is the first part.
	DataSectionOffset int64 `protobuf:"varint,5,opt,name=data_section_offset,json=dataSectionOffset,proto3" json:"data_section_offset,omitempty"` // Offset to the start of the data section.
	SkipIndexOffset   int64 `protobuf:"varint,6,opt,name=skip_index_offset,json=skipIndexOffset,proto3" json:"skip_index_offset,omitempty"`       // Offset to the start of the skip index section.
	BfIndexOffset     int64 `protobuf:"varint,7,opt,name=bf_index_offset,json=bfIndexOffset,proto3" json:"bf_index_offset,omitempty"`             // Offset to the start of the Bloom filter index section (0 if not present).
}

func (x *PartHeader) Reset() {
	*x = PartHeader{}
	if protoimpl.UnsafeEnabled {
		mi := &file_layout_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PartHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartHeader) ProtoMessage() {}

func (x *PartHeader) ProtoReflect() protoreflect.Message {
	mi := &file_layout_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartHeader.ProtoReflect.Descriptor instead.
func (*PartHeader) Descriptor() ([]byte, []int) {
	return file_layout_proto_rawDescGZIP(), []int{0}
}

func (x *PartHeader) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PartHeader) GetNextPart() int64 {
	if x != nil {
		return x.NextPart
	}
	return 0
}

func (x *PartHeader) GetPrevPart() int64 {
	if x != nil {
		return x.PrevPart
	}
	return 0
}

func (x *PartHeader) GetDataSectionOffset() int64 {
	if x != nil {
		return x.DataSectionOffset
	}
	return 0
}

func (x *PartHeader) GetSkipIndexOffset() int64 {
	if x != nil {
		return x.SkipIndexOffset
	}
	return 0
}

func (x *PartHeader) GetBfIndexOffset() int64 {
	if x != nil {
		return x.BfIndexOffset
	}
	return 0
}

type SkipIndex struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entries []*SkipIndex_Entry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"` // Sorted by key.
}

func (x *SkipIndex) Reset() {
	*x = SkipIndex{}
	if protoimpl.UnsafeEnabled {
		mi := &file_layout_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SkipIndex) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkipIndex) ProtoMessage() {}

func (x *SkipIndex) ProtoReflect() protoreflect.Message {
	mi := &file_layout_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkipIndex.ProtoReflect.Descriptor instead.
func (*SkipIndex) Descriptor() ([]byte, []int) {
	return file_layout_proto_rawDescGZIP(), []int{1}
}

func (x *SkipIndex) GetEntries() []*SkipIndex_Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type BloomFilterIndex struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NumBits      int64  `protobuf:"varint,1,opt,name=num_bits,json=numBits,proto3" json:"num_bits,omitempty"`                  // Number of bits in the Bloom filter.
	NumHashFuncs int32  `protobuf:"varint,2,opt,name=num_hash_funcs,json=numHashFuncs,proto3" json:"num_hash_funcs,omitempty"` // Number of hash functions used.
	BitArray     []byte `protobuf:"bytes,3,opt,name=bit_array,json=bitArray,proto3" json:"bit_array,omitempty"`                // Bit array representing the Bloom filter.
}

func (x *BloomFilterIndex) Reset() {
	*x = BloomFilterIndex{}
	if protoimpl.UnsafeEnabled {
		mi := &file_layout_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BloomFilterIndex) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BloomFilterIndex) ProtoMessage() {}

func (x *BloomFilterIndex) ProtoReflect() protoreflect.Message {
	mi := &file_layout_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BloomFilterIndex.ProtoReflect.Descriptor instead.
func (*BloomFilterIndex) Descriptor() ([]byte, []int) {
	return file_layout_proto_rawDescGZIP(), []int{2}
}

func (x *BloomFilterIndex) GetNumBits() int64 {
	if x != nil {
		return x.NumBits
	}
	return 0
}

func (x *BloomFilterIndex) GetNumHashFuncs() int32 {
	if x != nil {
		return x.NumHashFuncs
	}
	return 0
}

func (x *BloomFilterIndex) GetBitArray() []byte {
	if x != nil {
		return x.BitArray
	}
	return nil
}

type DataBlock struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KeyPrefix []byte             `protobuf:"bytes,1,opt,name=key_prefix,json=keyPrefix,proto3" json:"key_prefix,omitempty"` // Common prefix for all keys in this block.
	Entries   []*DataBlock_Entry `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`                      // Sorted by key.
}

func (x *DataBlock) Reset() {
	*x = DataBlock{}
	if protoimpl.UnsafeEnabled {
		mi := &file_layout_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataBlock) ProtoMessage() {}

func (x *DataBlock) ProtoReflect() protoreflect.Message {
	mi := &file_layout_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataBlock.ProtoReflect.Descriptor instead.
func (*DataBlock) Descriptor() ([]byte, []int) {
	return file_layout_proto_rawDescGZIP(), []int{3}
}

func (x *DataBlock) GetKeyPrefix() []byte {
	if x != nil {
		return x.KeyPrefix
	}
	return nil
}

func (x *DataBlock) GetEntries() []*DataBlock_Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type Gooz struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Api string `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
}

func (x *Gooz) Reset() {
	*x = Gooz{}
	if protoimpl.UnsafeEnabled {
		mi := &file_layout_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Gooz) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Gooz) ProtoMessage() {}

func (x *Gooz) ProtoReflect() protoreflect.Message {
	mi := &file_layout_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Gooz.ProtoReflect.Descriptor instead.
func (*Gooz) Descriptor() ([]byte, []int) {
	return file_layout_proto_rawDescGZIP(), []int{4}
}

func (x *Gooz) GetApi() string {
	if x != nil {
		return x.Api
	}
	return ""
}

type SkipIndex_Entry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key         []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`                                     // First key of the block.
	BlockOffset int64  `protobuf:"varint,2,opt,name=block_offset,json=blockOffset,proto3" json:"block_offset,omitempty"` // Offset to the start of the block in the data section.
	BlockSize   int32  `protobuf:"varint,3,opt,name=block_size,json=blockSize,proto3" json:"block_size,omitempty"`       // Size of the block in bytes.
}

func (x *SkipIndex_Entry) Reset() {
	*x = SkipIndex_Entry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_layout_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SkipIndex_Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkipIndex_Entry) ProtoMessage() {}

func (x *SkipIndex_Entry) ProtoReflect() protoreflect.Message {
	mi := &file_layout_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkipIndex_Entry.ProtoReflect.Descriptor instead.
func (*SkipIndex_Entry) Descriptor() ([]byte, []int) {
	return file_layout_proto_rawDescGZIP(), []int{1, 0}
}

func (x *SkipIndex_Entry) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *SkipIndex_Entry) GetBlockOffset() int64 {
	if x != nil {
		return x.BlockOffset
	}
	return 0
}

func (x *SkipIndex_Entry) GetBlockSize() int32 {
	if x != nil {
		return x.BlockSize
	}
	return 0
}

type DataBlock_Entry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *DataBlock_Entry) Reset() {
	*x = DataBlock_Entry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_layout_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataBlock_Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataBlock_Entry) ProtoMessage() {}

func (x *DataBlock_Entry) ProtoReflect() protoreflect.Message {
	mi := &file_layout_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataBlock_Entry.ProtoReflect.Descriptor instead.
func (*DataBlock_Entry) Descriptor() ([]byte, []int) {
	return file_layout_proto_rawDescGZIP(), []int{3, 0}
}

func (x *DataBlock_Entry) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *DataBlock_Entry) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

var File_layout_proto protoreflect.FileDescriptor

var file_layout_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x6c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04,
	0x6b, 0x69, 0x77, 0x69, 0x22, 0xda, 0x01, 0x0a, 0x0a, 0x50, 0x61, 0x72, 0x74, 0x48, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x6e, 0x65, 0x78, 0x74, 0x5f, 0x70, 0x61, 0x72, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x6e, 0x65, 0x78, 0x74, 0x50, 0x61, 0x72, 0x74,
	0x12, 0x1b, 0x0a, 0x09, 0x70, 0x72, 0x65, 0x76, 0x5f, 0x70, 0x61, 0x72, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x08, 0x70, 0x72, 0x65, 0x76, 0x50, 0x61, 0x72, 0x74, 0x12, 0x2e, 0x0a,
	0x13, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x73, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6f, 0x66,
	0x66, 0x73, 0x65, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x11, 0x64, 0x61, 0x74, 0x61,
	0x53, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x2a, 0x0a,
	0x11, 0x73, 0x6b, 0x69, 0x70, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x5f, 0x6f, 0x66, 0x66, 0x73,
	0x65, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0f, 0x73, 0x6b, 0x69, 0x70, 0x49, 0x6e,
	0x64, 0x65, 0x78, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x26, 0x0a, 0x0f, 0x62, 0x66, 0x5f,
	0x69, 0x6e, 0x64, 0x65, 0x78, 0x5f, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0d, 0x62, 0x66, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x4f, 0x66, 0x66, 0x73, 0x65,
	0x74, 0x22, 0x99, 0x01, 0x0a, 0x09, 0x53, 0x6b, 0x69, 0x70, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12,
	0x2f, 0x0a, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x15, 0x2e, 0x6b, 0x69, 0x77, 0x69, 0x2e, 0x53, 0x6b, 0x69, 0x70, 0x49, 0x6e, 0x64, 0x65,
	0x78, 0x2e, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73,
	0x1a, 0x5b, 0x0a, 0x05, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x21, 0x0a, 0x0c, 0x62,
	0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0b, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x1d,
	0x0a, 0x0a, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x09, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x53, 0x69, 0x7a, 0x65, 0x22, 0x70, 0x0a,
	0x10, 0x42, 0x6c, 0x6f, 0x6f, 0x6d, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x49, 0x6e, 0x64, 0x65,
	0x78, 0x12, 0x19, 0x0a, 0x08, 0x6e, 0x75, 0x6d, 0x5f, 0x62, 0x69, 0x74, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x07, 0x6e, 0x75, 0x6d, 0x42, 0x69, 0x74, 0x73, 0x12, 0x24, 0x0a, 0x0e,
	0x6e, 0x75, 0x6d, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x5f, 0x66, 0x75, 0x6e, 0x63, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x6e, 0x75, 0x6d, 0x48, 0x61, 0x73, 0x68, 0x46, 0x75, 0x6e,
	0x63, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x69, 0x74, 0x5f, 0x61, 0x72, 0x72, 0x61, 0x79, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x62, 0x69, 0x74, 0x41, 0x72, 0x72, 0x61, 0x79, 0x22,
	0x8c, 0x01, 0x0a, 0x09, 0x44, 0x61, 0x74, 0x61, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x1d, 0x0a,
	0x0a, 0x6b, 0x65, 0x79, 0x5f, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x09, 0x6b, 0x65, 0x79, 0x50, 0x72, 0x65, 0x66, 0x69, 0x78, 0x12, 0x2f, 0x0a, 0x07,
	0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e,
	0x6b, 0x69, 0x77, 0x69, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x2e, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x1a, 0x2f, 0x0a,
	0x05, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x18,
	0x0a, 0x04, 0x47, 0x6f, 0x6f, 0x7a, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x70, 0x69, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x61, 0x70, 0x69, 0x42, 0x22, 0x5a, 0x20, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6e, 0x6f, 0x62, 0x6c, 0x65, 0x74, 0x6f, 0x6f, 0x74,
	0x68, 0x2f, 0x6b, 0x69, 0x77, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_layout_proto_rawDescOnce sync.Once
	file_layout_proto_rawDescData = file_layout_proto_rawDesc
)

func file_layout_proto_rawDescGZIP() []byte {
	file_layout_proto_rawDescOnce.Do(func() {
		file_layout_proto_rawDescData = protoimpl.X.CompressGZIP(file_layout_proto_rawDescData)
	})
	return file_layout_proto_rawDescData
}

var file_layout_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_layout_proto_goTypes = []interface{}{
	(*PartHeader)(nil),       // 0: kiwi.PartHeader
	(*SkipIndex)(nil),        // 1: kiwi.SkipIndex
	(*BloomFilterIndex)(nil), // 2: kiwi.BloomFilterIndex
	(*DataBlock)(nil),        // 3: kiwi.DataBlock
	(*Gooz)(nil),             // 4: kiwi.Gooz
	(*SkipIndex_Entry)(nil),  // 5: kiwi.SkipIndex.Entry
	(*DataBlock_Entry)(nil),  // 6: kiwi.DataBlock.Entry
}
var file_layout_proto_depIdxs = []int32{
	5, // 0: kiwi.SkipIndex.entries:type_name -> kiwi.SkipIndex.Entry
	6, // 1: kiwi.DataBlock.entries:type_name -> kiwi.DataBlock.Entry
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_layout_proto_init() }
func file_layout_proto_init() {
	if File_layout_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_layout_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PartHeader); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_layout_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SkipIndex); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_layout_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BloomFilterIndex); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_layout_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataBlock); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_layout_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Gooz); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_layout_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SkipIndex_Entry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_layout_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataBlock_Entry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_layout_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_layout_proto_goTypes,
		DependencyIndexes: file_layout_proto_depIdxs,
		MessageInfos:      file_layout_proto_msgTypes,
	}.Build()
	File_layout_proto = out.File
	file_layout_proto_rawDesc = nil
	file_layout_proto_goTypes = nil
	file_layout_proto_depIdxs = nil
}
